name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch: ~

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: BaseMod

      - uses: CyberAndrii/setup-steamcmd@v1

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - run: mkdir lib/

      - name: Install Slay the Spire
        run: |
          mkdir SlayTheSpire/
          steamcmd +force_install_dir $(pwd)/SlayTheSpire/ +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +app_update 646570 +exit
          mv SlayTheSpire/desktop-1.0.jar lib/

      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /home/runner/Steam/logs/
        if: failure()

      - name: Build ModTheSpire
        run: |
          git clone --depth=1 https://github.com/kiooeht/ModTheSpire
          cd ModTheSpire
          chmod +x mvnw
          ./mvnw package

      - name: Build BaseMod
        run: |
          cd BaseMod
          mvn package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: BaseMod/mod/target/BaseMod.jar
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}