name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch: ~

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::219381348292:role/AmazonS3StSGetObject
          aws-region: us-east-1

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Build
        run: |
          mkdir ../lib
          cd ../lib
          aws s3api get-object --bucket slay-the-spire --key desktop-1.0.jar desktop-1.0.jar
          
          cd ..
          git clone --depth=1 https://github.com/kiooeht/ModTheSpire
          cd ModTheSpire
          chmod +x mvnw
          ./mvnw package
          
          cd ../BaseMod
          mvn package
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mod/target/BaseMod.jar