name: Steam Workshop Upload

on:
  release:
    types: [released]
  workflow_dispatch: ~

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: BaseMod.jar
          target: workshop-content/BaseMod.jar

      - uses: arma-actions/workshop-upload@v1
        with:
          appId: 646570
          itemId: 2778664982
          contentPath: workshop-content/
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}